# PostgreSQL configuration
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV["DATABASE_URL"] || "postgres://postgres:fallout@localhost:5432/fallout_development" %>

test:
  <<: *default
  url: <%= ENV["DATABASE_URL_TEST"] || "postgres://postgres:fallout@localhost:5432/fallout_test" %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
